Translated your first component
reactjs/hi.reactjs.org pull request #204
Opened 2022-04-16 10:40 UTC by Akshit1025

I have translated the **Your First Component** page. Please review it

**Sections on the page**
> * [ ] Intro
> 
> * [ ] Components: UI Building Blocks
> 
> * [ ] Defining a Component
>   * [ ] Step 1: Export the component
>   * [ ] Step 2: Define the function
>   * [ ] Step 3: Add Markup
> 
> * [ ] Using a component
>   * [ ] What the browser sees
>   * [ ] Nesting and Organising Components
> 
> * [ ] Recap
> 
> * [ ] Challenge
>   * [ ] Export the Component
>   * [ ] Fix the return statement
>   * [ ] Spot the Mistake
>   * [ ] Your Own Component

Please let me know if there are any changes that has to be made
Thank You

2022-05-03 19:04 UTC, Akshit1025 commented
@arshadkazmi42 please review this pull request

Thank You

2022-05-03 19:06 UTC, arshadkazmi42 commented
> @arshadkazmi42 please review this pull request
> 
> 
> 
> Thank You

@Akshit1025 I have been a bit busy. I will get to it soon. Sorry about the delay

2022-05-03 19:06 UTC, Akshit1025 commented
> > @arshadkazmi42 please review this pull request
> > Thank You
> 
> @Akshit1025 I have been a bit busy. I will get to it soon. Sorry about the delay

ok no problem

2022-05-10 07:27 UTC, arshadkazmi42 requested changes
Thank you for working on this.

I have added few comments till line 55

Lets' get these fixed and then I will continue with further review.

You can check for our review guidelines at #23

2022-05-10 07:27 UTC, arshadkazmi42 commented on beta/src/pages/learn/your-first-component.md
> +Web पर, HTML हमें `<h1>` और `<li>` जैसे टैग के अंतर्निहित सेट के साथ समृद्ध संरचित दस्तावेज़ बनाने देता है:
`समृद्ध संरचित दस्तावेज़` => `रिच स्ट्रक्चर्ड डाक्यूमेंट्स`

hindi translation seems a bit complex. lets keep it in hinglish

2022-05-10 07:27 UTC, arshadkazmi42 commented on beta/src/pages/learn/your-first-component.md
> +यह मार्कअप इस लेख `<article>`, इसके शीर्षक `<h1>`, और एक (संक्षिप्त) सामग्री तालिका को एक क्रमबद्ध सूची `<ol>` के रूप में दर्शाता है। इस तरह का मार्कअप, स्टाइल के लिए CSS के साथ संयुक्त, और जावास्क्र
`सामग्री तालिका` => `टेबल ऑफ़ कंटेंट्स`

2022-05-10 07:27 UTC, arshadkazmi42 commented on beta/src/pages/learn/your-first-component.md
> +यह मार्कअप इस लेख `<article>`, इसके शीर्षक `<h1>`, और एक (संक्षिप्त) सामग्री तालिका को एक क्रमबद्ध सूची `<ol>` के रूप में दर्शाता है। इस तरह का मार्कअप, स्टाइल के लिए CSS के साथ संयुक्त, और जावास्क्र
`लेख` => `आर्टिकल`

2022-05-10 07:27 UTC, arshadkazmi42 commented on beta/src/pages/learn/your-first-component.md
> +यह मार्कअप इस लेख `<article>`, इसके शीर्षक `<h1>`, और एक (संक्षिप्त) सामग्री तालिका को एक क्रमबद्ध सूची `<ol>` के रूप में दर्शाता है। इस तरह का मार्कअप, स्टाइल के लिए CSS के साथ संयुक्त, और जावास्क्र
`संयुक्त` => `मिला के`

2022-05-10 07:27 UTC, arshadkazmi42 commented on beta/src/pages/learn/your-first-component.md
> +यह मार्कअप इस लेख `<article>`, इसके शीर्षक `<h1>`, और एक (संक्षिप्त) सामग्री तालिका को एक क्रमबद्ध सूची `<ol>` के रूप में दर्शाता है। इस तरह का मार्कअप, स्टाइल के लिए CSS के साथ संयुक्त, और जावास्क्र
`अन्तरक्रियाशीलता` => `इंटरएक्टिविटी`

2022-05-10 07:27 UTC, arshadkazmi42 commented on beta/src/pages/learn/your-first-component.md
> +यह मार्कअप इस लेख `<article>`, इसके शीर्षक `<h1>`, और एक (संक्षिप्त) सामग्री तालिका को एक क्रमबद्ध सूची `<ol>` के रूप में दर्शाता है। इस तरह का मार्कअप, स्टाइल के लिए CSS के साथ संयुक्त, और जावास्क्र
`निहित` => `रहता`

2022-05-10 07:27 UTC, arshadkazmi42 commented on beta/src/pages/learn/your-first-component.md
> +React आपको अपने मार्कअप, CSS और जावास्क्रिप्ट को कस्टम "कौम्पोनॅन्ट," **आपके एप्प के लिए पुन: प्रयोज्य `UI` तत्वों में संयोजित करने देता है। ** ऊपर देखी गई सामग्री कोड की तालिका को `<TableOfContents
`**आपके एप्प के लिए पुन: प्रयोज्य `UI` तत्वों में संयोजित करने देता है। **` => `**आपके एप्प के लिए री-यूज़ब्ले UI एलिमेंट्स** में संयोजित करने देता है।`

2022-05-10 07:27 UTC, arshadkazmi42 commented on beta/src/pages/learn/your-first-component.md
> +React आपको अपने मार्कअप, CSS और जावास्क्रिप्ट को कस्टम "कौम्पोनॅन्ट," **आपके एप्प के लिए पुन: प्रयोज्य `UI` तत्वों में संयोजित करने देता है। ** ऊपर देखी गई सामग्री कोड की तालिका को `<TableOfContents
`सामग्री कोड की तालिका` => `टेबल ऑफ़ कंटेंट्स कोड`

2022-05-10 07:27 UTC, arshadkazmi42 commented on beta/src/pages/learn/your-first-component.md
> +React आपको अपने मार्कअप, CSS और जावास्क्रिप्ट को कस्टम "कौम्पोनॅन्ट," **आपके एप्प के लिए पुन: प्रयोज्य `UI` तत्वों में संयोजित करने देता है। ** ऊपर देखी गई सामग्री कोड की तालिका को `<TableOfContents
`है आप` => `है जो आप`

2022-05-10 07:27 UTC, arshadkazmi42 commented on beta/src/pages/learn/your-first-component.md
> +React आपको अपने मार्कअप, CSS और जावास्क्रिप्ट को कस्टम "कौम्पोनॅन्ट," **आपके एप्प के लिए पुन: प्रयोज्य `UI` तत्वों में संयोजित करने देता है। ** ऊपर देखी गई सामग्री कोड की तालिका को `<TableOfContents
```
हुड के तहत, यह अभी भी उसी HTML टैग का उपयोग करता है जैसे `<article>`, `<h1>`, आदि।
```
=>
```
अंडर हुड, यह अभी भी HTML टैग जैसे `<article>`, `<h1>`, आदि का उपयोग करता है।
```

2022-05-10 07:27 UTC, arshadkazmi42 commented on beta/src/pages/learn/your-first-component.md
> +HTML टैग्स की तरह ही, आप संपूर्ण पेज को डिज़ाइन करने के लिए कौम्पोनॅन्ट को कंपोज़, ऑर्डर और नेस्ट कर सकते हैं। उदाहरण के लिए, आप जिस दस्तावेज़ पेज को पढ़ रहे हैं वह React कौम्पोनॅन्ट से बना है:
`दस्तावेज़` => `डॉक्यूमेंटेशन`

2022-05-10 07:27 UTC, arshadkazmi42 commented on beta/src/pages/learn/your-first-component.md
> +जैसे-जैसे आपकी परियोजना बढ़ती है, आप देखेंगे कि आपके कई डिज़ाइन आपके द्वारा पहले से लिखे गए कौम्पोनॅन्ट का पुन: उपयोग करके, आपके विकास को गति देकर बनाए जा सकते हैं। ऊपर दी गई हमारी सामग्री तालिका `<T
`आपकी परियोजना बढ़ती` => `आपका प्रोजेक्ट बढ़ता`

2022-05-10 07:27 UTC, arshadkazmi42 commented on beta/src/pages/learn/your-first-component.md
> +जैसे-जैसे आपकी परियोजना बढ़ती है, आप देखेंगे कि आपके कई डिज़ाइन आपके द्वारा पहले से लिखे गए कौम्पोनॅन्ट का पुन: उपयोग करके, आपके विकास को गति देकर बनाए जा सकते हैं। ऊपर दी गई हमारी सामग्री तालिका `<T
`आपके विकास को गति देकर बनाए जा सकते हैं।` => `आपके डेवलपमेंट की गति को बढ़ाते हैं।`

2022-05-10 07:27 UTC, arshadkazmi42 commented on beta/src/pages/learn/your-first-component.md
> +जैसे-जैसे आपकी परियोजना बढ़ती है, आप देखेंगे कि आपके कई डिज़ाइन आपके द्वारा पहले से लिखे गए कौम्पोनॅन्ट का पुन: उपयोग करके, आपके विकास को गति देकर बनाए जा सकते हैं। ऊपर दी गई हमारी सामग्री तालिका `<T
`दी गई हमारी सामग्री तालिका` => `दिए गए हमारे टेबल ऑफ़ कंटेंट्स`

2022-05-10 07:27 UTC, arshadkazmi42 commented on beta/src/pages/learn/your-first-component.md
> +जैसे-जैसे आपकी परियोजना बढ़ती है, आप देखेंगे कि आपके कई डिज़ाइन आपके द्वारा पहले से लिखे गए कौम्पोनॅन्ट का पुन: उपयोग करके, आपके विकास को गति देकर बनाए जा सकते हैं। ऊपर दी गई हमारी सामग्री तालिका `<T
`जोड़ी` => `ऐड किया जा सकता है`

2022-05-10 07:27 UTC, arshadkazmi42 commented on beta/src/pages/learn/your-first-component.md
> +जैसे-जैसे आपकी परियोजना बढ़ती है, आप देखेंगे कि आपके कई डिज़ाइन आपके द्वारा पहले से लिखे गए कौम्पोनॅन्ट का पुन: उपयोग करके, आपके विकास को गति देकर बनाए जा सकते हैं। ऊपर दी गई हमारी सामग्री तालिका `<T
`समुदाय` => `कम्युनिटी`

2022-05-10 07:27 UTC, arshadkazmi42 commented on beta/src/pages/learn/your-first-component.md
> +जैसे-जैसे आपकी परियोजना बढ़ती है, आप देखेंगे कि आपके कई डिज़ाइन आपके द्वारा पहले से लिखे गए कौम्पोनॅन्ट का पुन: उपयोग करके, आपके विकास को गति देकर बनाए जा सकते हैं। ऊपर दी गई हमारी सामग्री तालिका `<T
`साझा` => `शेयर`

2022-05-10 07:27 UTC, arshadkazmi42 commented on beta/src/pages/learn/your-first-component.md
> +जैसे-जैसे आपकी परियोजना बढ़ती है, आप देखेंगे कि आपके कई डिज़ाइन आपके द्वारा पहले से लिखे गए कौम्पोनॅन्ट का पुन: उपयोग करके, आपके विकास को गति देकर बनाए जा सकते हैं। ऊपर दी गई हमारी सामग्री तालिका `<T
`अपनी परियोजना` => `अपने प्रोजेक्ट`

2022-05-10 07:27 UTC, arshadkazmi42 commented on beta/src/pages/learn/your-first-component.md
> +जैसे-जैसे आपकी परियोजना बढ़ती है, आप देखेंगे कि आपके कई डिज़ाइन आपके द्वारा पहले से लिखे गए कौम्पोनॅन्ट का पुन: उपयोग करके, आपके विकास को गति देकर बनाए जा सकते हैं। ऊपर दी गई हमारी सामग्री तालिका `<T
`को शुरू भी कर` => `को एक शुरुआत दे`

2022-05-30 06:46 UTC, arshadkazmi42 commented on beta/src/pages/learn/your-first-component.md
> +यह मार्कअप इस लेख `<article>`, इसके शीर्षक `<h1>`, और एक (संक्षिप्त) सामग्री तालिका को एक क्रमबद्ध सूची `<ol>` के रूप में दर्शाता है। इस तरह का मार्कअप, स्टाइल के लिए CSS के साथ संयुक्त, और जावास्क्र
@Akshit1025 There is a typo here.

`सटेबल ऑफ़ कंटेंट्सा` => `टेबल ऑफ़ कंटेंट्स`

2022-05-30 06:46 UTC, arshadkazmi42 commented on beta/src/pages/learn/your-first-component.md
> +यह मार्कअप इस लेख `<article>`, इसके शीर्षक `<h1>`, और एक (संक्षिप्त) सामग्री तालिका को एक क्रमबद्ध सूची `<ol>` के रूप में दर्शाता है। इस तरह का मार्कअप, स्टाइल के लिए CSS के साथ संयुक्त, और जावास्क्र
@Akshit1025 Typo here. Can you please check once

2022-05-30 06:47 UTC, arshadkazmi42 commented on beta/src/pages/learn/your-first-component.md
> +React आपको अपने मार्कअप, CSS और जावास्क्रिप्ट को कस्टम "कौम्पोनॅन्ट," **आपके एप्प के लिए पुन: प्रयोज्य `UI` तत्वों में संयोजित करने देता है। ** ऊपर देखी गई सामग्री कोड की तालिका को `<TableOfContents
@Akshit1025 typo here

2022-05-30 06:49 UTC, arshadkazmi42 commented on beta/src/pages/learn/your-first-component.md
> +जैसे-जैसे आपकी परियोजना बढ़ती है, आप देखेंगे कि आपके कई डिज़ाइन आपके द्वारा पहले से लिखे गए कौम्पोनॅन्ट का पुन: उपयोग करके, आपके विकास को गति देकर बनाए जा सकते हैं। ऊपर दी गई हमारी सामग्री तालिका `<T
@Akshit1025 Typo here

2022-05-30 06:50 UTC, arshadkazmi42 commented
@Akshit1025 There are few typo. I have marked them as unresolved.

Can you cross check those and post that I will start reviewing the rest of the PR

2022-07-09 09:46 UTC, Akshit1025 commented
@arshadkazmi42 Hey sorry for responding really late but I have fixed the typos that you have asked me to do so please carry on with the reviewing of the file

Thanks

2022-07-11 05:08 UTC, arshadkazmi42 requested changes
Added review comments till line 81. 

Let's get these fixed and then we can start the review of rest of the file.

2022-07-11 05:08 UTC, arshadkazmi42 commented on beta/src/pages/learn/your-first-component.md
> +### Step 1: कौम्पोनॅन्ट निर्यात करें {/* step-1-export-the-component */}
`निर्यात` => `एक्सपोर्ट`

2022-07-11 05:08 UTC, arshadkazmi42 commented on beta/src/pages/learn/your-first-component.md
> +### Step 1: कौम्पोनॅन्ट निर्यात करें {/* step-1-export-the-component */}
`{/* step-1-export-the-component */}` => `{/*step-1-export-the-component*/}`

2022-07-11 05:08 UTC, arshadkazmi42 commented on beta/src/pages/learn/your-first-component.md
> +`export default` उपसर्ग एक [standard JavaScript syntax](https://developer.mozilla.org/docs/web/javascript/reference/statements/export) है (React के लिए विशिष्ट नहीं)। यह आपको फ़ाइल में मुख्य फ़ंक्शन
`उपसर्ग` => `प्रीफिक्स`

2022-07-11 05:08 UTC, arshadkazmi42 commented on beta/src/pages/learn/your-first-component.md
> +`export default` उपसर्ग एक [standard JavaScript syntax](https://developer.mozilla.org/docs/web/javascript/reference/statements/export) है (React के लिए विशिष्ट नहीं)। यह आपको फ़ाइल में मुख्य फ़ंक्शन
`standard JavaScript syntax` => `स्टैण्डर्ड जावास्क्रिप्ट सिंटेक्स`

2022-07-11 05:08 UTC, arshadkazmi42 commented on beta/src/pages/learn/your-first-component.md
> +`export default` उपसर्ग एक [standard JavaScript syntax](https://developer.mozilla.org/docs/web/javascript/reference/statements/export) है (React के लिए विशिष्ट नहीं)। यह आपको फ़ाइल में मुख्य फ़ंक्शन
`विशिष्ट` => `स्पेसिफिक`

2022-07-11 05:08 UTC, arshadkazmi42 commented on beta/src/pages/learn/your-first-component.md
> +`export default` उपसर्ग एक [standard JavaScript syntax](https://developer.mozilla.org/docs/web/javascript/reference/statements/export) है (React के लिए विशिष्ट नहीं)। यह आपको फ़ाइल में मुख्य फ़ंक्शन
`मुख्य` => `मैन`

2022-07-11 05:08 UTC, arshadkazmi42 commented on beta/src/pages/learn/your-first-component.md
> +`export default` उपसर्ग एक [standard JavaScript syntax](https://developer.mozilla.org/docs/web/javascript/reference/statements/export) है (React के लिए विशिष्ट नहीं)। यह आपको फ़ाइल में मुख्य फ़ंक्शन
`चिह्नित` => `मार्क`

2022-07-11 05:08 UTC, arshadkazmi42 commented on beta/src/pages/learn/your-first-component.md
> +`export default` उपसर्ग एक [standard JavaScript syntax](https://developer.mozilla.org/docs/web/javascript/reference/statements/export) है (React के लिए विशिष्ट नहीं)। यह आपको फ़ाइल में मुख्य फ़ंक्शन
`आयात` => `इम्पोर्ट`

2022-07-11 05:08 UTC, arshadkazmi42 commented on beta/src/pages/learn/your-first-component.md
> +`export default` उपसर्ग एक [standard JavaScript syntax](https://developer.mozilla.org/docs/web/javascript/reference/statements/export) है (React के लिए विशिष्ट नहीं)। यह आपको फ़ाइल में मुख्य फ़ंक्शन
`Importing and Exporting Components` => `इम्पॉर्टिंग एंड एक्सपोर्टिंग कौम्पोनॅन्टस`

2022-07-11 05:08 UTC, arshadkazmi42 commented on beta/src/pages/learn/your-first-component.md
> +`export default` उपसर्ग एक [standard JavaScript syntax](https://developer.mozilla.org/docs/web/javascript/reference/statements/export) है (React के लिए विशिष्ट नहीं)। यह आपको फ़ाइल में मुख्य फ़ंक्शन
`आयात करने पर अधिक!` => `इम्पॉर्टिंग के बारे में और अधिक जानें!`

2022-08-13 11:50 UTC, Akshit1025 commented
@arshadkazmi42 I have resolved the typos you have pointed out
please check out

sorry for responding late as I had school too

2022-09-08 15:53 UTC, arshadkazmi42 requested changes
Thank you for working on the fixes.

I have added more review comments till line 120.

Once these are fixed, we can continue further with the review.

2022-09-08 15:53 UTC, arshadkazmi42 commented on beta/src/pages/learn/your-first-component.md
> +### Step 3: मार्कअप जोड़ें {/*step-3-add-markup*/}
`जोड़ें` => `ऐड करें`

2022-09-08 15:53 UTC, arshadkazmi42 commented on beta/src/pages/learn/your-first-component.md
> +कौम्पोनॅन्ट `src` और `alt` विशेषताओं के साथ एक `<img />` टैग देता है। `<img />` HTML की तरह लिखा गया है, लेकिन वास्तव में यह जावास्क्रिप्ट है! इस सिंटैक्स को [JSX](/learn/writing-markup-with-jsx) कहा
`टैग देता है` => `रिटर्न करता है`

2022-09-09 04:46 UTC, Akshit1025 commented
@arshadkazmi42 I have fixed the typos. You can now start reviewing them further

thanks

2022-09-15 14:26 UTC, arshadkazmi42 requested changes
Thank you for working on the fixes.

I have added more review comments till line 170.

Let's get these fixed, post that we can continue further with the review

2022-09-15 14:26 UTC, arshadkazmi42 commented on beta/src/pages/learn/your-first-component.md
> +## एक कौम्पोनॅन्ट का उपयोग करना {/* using-a-component */}
`{/* using-a-component */}` => `{/*using-a-component*/}`

Let's not make any changes to these. These will be used for reflinks

2022-09-15 14:26 UTC, arshadkazmi42 commented on beta/src/pages/learn/your-first-component.md
> +अब जब आपने अपना `Profile` कौम्पोनॅन्ट परिभाषित कर लिया है, तो आप इसे अन्य कौम्पोनॅन्ट के अंदर घोंसला बना सकते हैं। उदाहरण के लिए, आप एक `Gallery` कौम्पोनॅन्ट निर्यात कर सकते हैं जो एकाधिक `Profile` क
`परिभाषित` => `डिफाइन`

2022-09-15 14:26 UTC, arshadkazmi42 commented on beta/src/pages/learn/your-first-component.md
> +अब जब आपने अपना `Profile` कौम्पोनॅन्ट परिभाषित कर लिया है, तो आप इसे अन्य कौम्पोनॅन्ट के अंदर घोंसला बना सकते हैं। उदाहरण के लिए, आप एक `Gallery` कौम्पोनॅन्ट निर्यात कर सकते हैं जो एकाधिक `Profile` क
`घोंसला बना` => `इस्तेमाल`

2022-09-15 14:26 UTC, arshadkazmi42 commented on beta/src/pages/learn/your-first-component.md
> +अब जब आपने अपना `Profile` कौम्पोनॅन्ट परिभाषित कर लिया है, तो आप इसे अन्य कौम्पोनॅन्ट के अंदर घोंसला बना सकते हैं। उदाहरण के लिए, आप एक `Gallery` कौम्पोनॅन्ट निर्यात कर सकते हैं जो एकाधिक `Profile` क
`निर्यात` => `एक्सपोर्ट`

2022-09-15 14:26 UTC, arshadkazmi42 commented on beta/src/pages/learn/your-first-component.md
> +अब जब आपने अपना `Profile` कौम्पोनॅन्ट परिभाषित कर लिया है, तो आप इसे अन्य कौम्पोनॅन्ट के अंदर घोंसला बना सकते हैं। उदाहरण के लिए, आप एक `Gallery` कौम्पोनॅन्ट निर्यात कर सकते हैं जो एकाधिक `Profile` क
`एकाधिक` => `एक से ज़्यादा`

2022-09-15 14:26 UTC, arshadkazmi42 commented on beta/src/pages/learn/your-first-component.md
> +  return <img src="https://i.imgur.com/MK3eW3As.jpg" alt="Katherine Johnson" />;
Let's not change any code alignments 

```
  return (
    <img
      src="https://i.imgur.com/MK3eW3As.jpg"
      alt="Katherine Johnson"
    />
  );
```

2022-09-15 14:26 UTC, arshadkazmi42 commented on beta/src/pages/learn/your-first-component.md
> +img {
same as above. lets not change any code alignments

```
img { margin: 0 10px 10px 0; height: 90px; }
```

2022-09-15 14:26 UTC, arshadkazmi42 commented on beta/src/pages/learn/your-first-component.md
> +### ब्राउज़र क्या देखता है {/* what-the-browser-sees */}
`{/* what-the-browser-sees */}` => `{/*what-the-browser-sees*/}`

2022-09-15 14:26 UTC, arshadkazmi42 commented on beta/src/pages/learn/your-first-component.md
> +आवरण में अंतर पर ध्यान दें:
`आवरण` => `केसिंग`

2022-09-15 14:26 UTC, arshadkazmi42 commented on beta/src/pages/learn/your-first-component.md
> +- `<section>` लोअरकेस है, इसलिए React जानता है कि हम एक HTML टैग को संदर्भित करते हैं।
```
- `<section>`
```
=>
```
* `<section>`
```

2022-09-15 14:26 UTC, arshadkazmi42 commented on beta/src/pages/learn/your-first-component.md
> +- `<section>` लोअरकेस है, इसलिए React जानता है कि हम एक HTML टैग को संदर्भित करते हैं।
`संदर्भित` => `रेफेर`

2022-09-15 14:26 UTC, arshadkazmi42 commented on beta/src/pages/learn/your-first-component.md
> +- `<section>` लोअरकेस है, इसलिए React जानता है कि हम एक HTML टैग को संदर्भित करते हैं।
`करते` => `कर रहे`

2022-09-15 14:26 UTC, arshadkazmi42 commented on beta/src/pages/learn/your-first-component.md
> +- `<Profile />` पूंजी `P` से शुरू होता है, इसलिए React जानता है कि हम `Profile` नामक हमारे कौम्पोनॅन्ट का उपयोग करना चाहते हैं।
```
- `<Profile />`
```
=>
```
* `<Profile />`
```

2022-09-15 14:26 UTC, arshadkazmi42 commented on beta/src/pages/learn/your-first-component.md
> +- `<Profile />` पूंजी `P` से शुरू होता है, इसलिए React जानता है कि हम `Profile` नामक हमारे कौम्पोनॅन्ट का उपयोग करना चाहते हैं।
`पूंजी` => `कैपिटल`

2022-12-04 09:53 UTC, Akshit1025 commented
@arshadkazmi42 I have fixed the typos and now you can further review the translation

2022-12-04 11:50 UTC, arshadkazmi42 commented on beta/src/pages/learn/your-first-component.md
> +  return <img src="https://i.imgur.com/MK3eW3As.jpg" alt="Katherine Johnson" />;
This still has some spaces wrong. You can check the below screenshot

![Screenshot from 2022-12-04 12-49-40](https://user-images.githubusercontent.com/4654382/205488705-383cc0cf-9078-4c57-a537-e1a3670b0e7c.png)

You can copy paste from the original version from [here](https://github.com/reactjs/hi.reactjs.org/pull/204/files#diff-987109509fdb76c4b375a50d1545ac66a321a4dbfb786d5fe75c84760e30b7fdL130-L134)

2022-12-04 11:51 UTC, arshadkazmi42 commented on beta/src/pages/learn/your-first-component.md
> +img {
This is not fixed correctly. You can copy the original version from left side [here](https://github.com/reactjs/hi.reactjs.org/pull/204/files#diff-987109509fdb76c4b375a50d1545ac66a321a4dbfb786d5fe75c84760e30b7fdL150)

2022-12-04 11:53 UTC, arshadkazmi42 commented
@Akshit1025 There are two review comments which still have minor issues. Rest looks fine.

I have marked them as unresolved, can you check and update those? Post that we can continue further.

2022-12-04 21:18 UTC, arshadkazmi42 commented on beta/src/pages/learn/your-first-component.md
> +  return <img src="https://i.imgur.com/MK3eW3As.jpg" alt="Katherine Johnson" />;
There is still one typo in this. The semicolon `;` is at wrong place

```
function Profile() {
  return (
    <img 
      src="https://i.imgur.com/MK3eW3As.jpg" 
      alt="Katherine Johnson" 
    />;
  )
}
```
=>
```
function Profile() {
  return (
    <img
      src="https://i.imgur.com/MK3eW3As.jpg"
      alt="Katherine Johnson"
    />
  );
}
```
```

2022-12-04 21:19 UTC, arshadkazmi42 commented
@Akshit1025 There is still one typo in the code block. Please check the unresolved comment

2022-12-06 14:02 UTC, Akshit1025 commented
@arshadkazmi42 typos have been fixed. Please carry on

2022-12-07 20:02 UTC, arshadkazmi42 requested changes
Thank you for working on the fixes.

I have added review in rest of the file.

Once these are fixed we can get this merged.

2022-12-07 20:02 UTC, arshadkazmi42 commented on beta/src/pages/learn/your-first-component.md
> +img {
```suggestion
img { margin: 0 10px 10px 0; }
```

2022-12-07 20:02 UTC, arshadkazmi42 commented on beta/src/pages/learn/your-first-component.md
> +  margin: 0 10px 10px 0;
```suggestion
```

2022-12-07 20:02 UTC, arshadkazmi42 commented on beta/src/pages/learn/your-first-component.md
> +}
```suggestion
```

2022-12-07 20:02 UTC, arshadkazmi42 commented on beta/src/pages/learn/your-first-component.md
> +Scratch से एक कौम्पोनॅन्ट लिखें। आप इसे कोई भी मान्य नाम दे सकते हैं और कोई मार्कअप वापस कर सकते हैं। यदि आपके पास विचार नहीं हैं, तो आप एक `Congratulations` कौम्पोनॅन्ट लिख सकते हैं जो `<h1>Good job
```suggestion
बिलकुल शुरू से एक कौम्पोनॅन्ट लिखें। आप इसे कोई भी वैलिड नाम दे सकते हैं और कोई मार्कअप रिटर्न कर सकते हैं। यदि आपके पास कोई आईडिया नहीं हैं, तो आप एक `Congratulations` कौम्पोनॅन्ट लिख सकते हैं जो `<h1>Good job!</h1>` दिखाता है। इसे एक्सपोर्ट करना न भूलें!
```

2022-12-07 20:02 UTC, arshadkazmi42 commented on beta/src/pages/learn/your-first-component.md
> +  return <h1>Good job!</h1>;
```suggestion
  return (
    <h1>Good job!</h1>
  );
```

2022-12-07 20:03 UTC, arshadkazmi42 requested changes
Thank you for working on the fixes.

I have added review in rest of the file.

Once these are fixed we can get this merged.

2022-12-08 08:42 UTC, Akshit1025 commented
@arshadkazmi42 all the typos that you have suggested have been completed

2022-12-08 20:07 UTC, arshadkazmi42 approved these changes
Great work. Thank you for working on all the fixes.

lets get this merged :tada:

2022-12-08 20:17 UTC, merged