translated till line 50
reactjs/hi.reactjs.org pull request #211
Opened 2022-08-23 14:19 UTC by Akshat2Jain

Hey, @arshadkazmi42 I have translated till line 50. Plz, review it so that I can keep continuing the translation.

2022-08-23 14:22 UTC, arshadkazmi42 commented
Thank you @Akshat2Jain for working on this.

But we follow the process of translating the whole page and then reviewing it in parts. We faced issues before when we were trying to do translations in part. 

So I would suggest, please work on translating the whole file then we can start with the review.

2022-08-23 14:43 UTC, Akshat2Jain commented
ok, @arshadkazmi42 sir

2022-09-01 18:47 UTC, arshadkazmi42 commented
> Hey, @arshadkazmi42 I have translated the " updating the objects in the state " page into Hindi. Please review it.

Thank you @Akshat2Jain I will get it ASAP

2022-09-08 13:19 UTC, Akshat2Jain commented
Hey @arshadkazmi42 sir, How much time will take it for review?

2022-09-08 14:02 UTC, arshadkazmi42 commented
> Hey @arshadkazmi42 sir, How much time will take it for review?

@Akshat2Jain I will start on the review ASAP

2022-09-09 09:39 UTC, arshadkazmi42 requested changes
Thank you for working on this.

I have added review till line 19

Let's get these fixed then we can continue with further review process.

To know more about our review process you can refer #23

2022-09-09 09:39 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +स्टेट कोई भी जावास्क्रिप्ट वैल्यू स्टोर करसकती है, ऑब्जेक्ट समेत। लेकिन आपको कभी भी  ऑब्जेक्ट्स को बदलना नहीं चैयाह जो आप React स्टेट में होल्ड करते है। उसके बजाए आपको जब भी  ऑब्जेक्ट को अपडेट करना ह
`स्टेट कोई भी जावास्क्रिप्ट वैल्यू स्टोर करसकती है, ऑब्जेक्ट समेत।` => `स्टेट ऑब्जेक्ट समेत कोई भी जावास्क्रिप्ट वैल्यू स्टोर कर सकती है।`

2022-09-09 09:39 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +स्टेट कोई भी जावास्क्रिप्ट वैल्यू स्टोर करसकती है, ऑब्जेक्ट समेत। लेकिन आपको कभी भी  ऑब्जेक्ट्स को बदलना नहीं चैयाह जो आप React स्टेट में होल्ड करते है। उसके बजाए आपको जब भी  ऑब्जेक्ट को अपडेट करना ह
`चैयाह` => `चाहिए`

2022-09-09 09:39 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +स्टेट कोई भी जावास्क्रिप्ट वैल्यू स्टोर करसकती है, ऑब्जेक्ट समेत। लेकिन आपको कभी भी  ऑब्जेक्ट्स को बदलना नहीं चैयाह जो आप React स्टेट में होल्ड करते है। उसके बजाए आपको जब भी  ऑब्जेक्ट को अपडेट करना ह
`स्टेट में होल्ड करते है।` => `स्टेट में रखते हैं।`

2022-09-09 09:39 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +स्टेट कोई भी जावास्क्रिप्ट वैल्यू स्टोर करसकती है, ऑब्जेक्ट समेत। लेकिन आपको कभी भी  ऑब्जेक्ट्स को बदलना नहीं चैयाह जो आप React स्टेट में होल्ड करते है। उसके बजाए आपको जब भी  ऑब्जेक्ट को अपडेट करना ह
`बनाये या उसी की एक कॉपी बनाये और` => `बनाये (या उसी की एक कॉपी बनाये) और`

2022-09-09 09:39 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +स्टेट कोई भी जावास्क्रिप्ट वैल्यू स्टोर करसकती है, ऑब्जेक्ट समेत। लेकिन आपको कभी भी  ऑब्जेक्ट्स को बदलना नहीं चैयाह जो आप React स्टेट में होल्ड करते है। उसके बजाए आपको जब भी  ऑब्जेक्ट को अपडेट करना ह
`फिर स्टेट को सेट करदे उस कॉपी का उपयोग करने के लिये।` => `फिर उस कॉपी का उपयोग करने के लिये स्टेट को सेट कर दें।`

2022-09-09 09:39 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +- इम्म्यूटेबलिटी  क्या होती है और कैसे उसे न तोड़े
`न तोड़े` => `ब्रेक ना करें`

2022-09-09 09:39 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +- Immer की मदद से एक जैसे ऑब्जेक्टस को बार-बार कम कैसे बनाये
`जैसे ऑब्जेक्टस को बार-बार कम कैसे बनाये` => `बार-बार ऑब्जेक्टस की कॉपी बनाने को काम कैसे करें`

2022-09-09 13:04 UTC, Akshat2Jain commented
hey @arshadkazmi42 sir, I have updated the changes.

2022-09-09 13:07 UTC, Akshat2Jain commented
sorry by mistake I resolved the conversation, but then I unresolved it again

2022-09-12 15:30 UTC, Akshat2Jain commented
Hey @arshadkazmi42 sir plz review the changes so that we can move forward

2022-09-12 18:30 UTC, arshadkazmi42 commented
@Akshat2Jain Thank you for working on the fixes. I will get to is soon

2022-09-15 10:36 UTC, arshadkazmi42 requested changes
Thank you for working on this fixes. 

I have added few more comments till line 104.

Let's get these fixed, then we can continue further with the review.

2022-09-15 10:36 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +## म्युटेशन क्या होती है ?  {/*whats-a-mutation*/}
`होती है ?` => `होता है?`

2022-09-15 10:36 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +अभी तक आप नंबर्स, स्ट्रिंग्स, और बूलियन के साथ काम कर रहे थे। ऐसी जावास्क्रिप्ट वैल्यूज " इम्म्यूटेबल " होती है,  मतलब जो कभी बदल न सके या " रीड-ओनली " हो। आप रीरेंदर ट्रिगर करसकते है वैल्यू को _ब्दल
`" इम्म्यूटेबल "` => `"इम्म्यूटेबल"`

2022-09-15 10:36 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +अभी तक आप नंबर्स, स्ट्रिंग्स, और बूलियन के साथ काम कर रहे थे। ऐसी जावास्क्रिप्ट वैल्यूज " इम्म्यूटेबल " होती है,  मतलब जो कभी बदल न सके या " रीड-ओनली " हो। आप रीरेंदर ट्रिगर करसकते है वैल्यू को _ब्दल
`" रीड-ओनली "` => `"रीड-ओनली"`

2022-09-15 10:36 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +अभी तक आप नंबर्स, स्ट्रिंग्स, और बूलियन के साथ काम कर रहे थे। ऐसी जावास्क्रिप्ट वैल्यूज " इम्म्यूटेबल " होती है,  मतलब जो कभी बदल न सके या " रीड-ओनली " हो। आप रीरेंदर ट्रिगर करसकते है वैल्यू को _ब्दल
`आप रीरेंदर ट्रिगर करसकते है वैल्यू को _ब्दलने_ के लिया।` => `वैल्यू को _ब्दलने_ के लिए आप री-रेंडर ट्रिगर करसकते है।`

2022-09-15 10:36 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +तकनीकी ओर से यह मुमकिन है की _खुदी ऑब्जेक्ट_ के कंटेंट को चेंज करसके।  **यही म्युटेशन कहलाता है:**
`चेंज करसके।` => `चेंज कर सकते हैं।`

2022-09-15 10:36 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +हलाक, जबकि React स्टेट में ऑब्जेक्ट्स तकनीकी रूप से मुटेबल होते है, आपको उनके साथ ऐसे व्यवहार करना चैयाह **जैसे वो** इम्म्यूटेबल हो नंबर्स, बूलियनस, और स्ट्रिंग्स की तरह। उनको म्यूटेट करने की बजाए, आ
`इम्म्यूटेबल हो नंबर्स` => `इम्म्यूटेबल हो--नंबर्स`

2022-09-15 10:36 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +हलाक, जबकि React स्टेट में ऑब्जेक्ट्स तकनीकी रूप से मुटेबल होते है, आपको उनके साथ ऐसे व्यवहार करना चैयाह **जैसे वो** इम्म्यूटेबल हो नंबर्स, बूलियनस, और स्ट्रिंग्स की तरह। उनको म्यूटेट करने की बजाए, आ
`ररिप्लेस` => `रीप्लेस`

2022-09-15 10:36 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +हलाक, जबकि React स्टेट में ऑब्जेक्ट्स तकनीकी रूप से मुटेबल होते है, आपको उनके साथ ऐसे व्यवहार करना चैयाह **जैसे वो** इम्म्यूटेबल हो नंबर्स, बूलियनस, और स्ट्रिंग्स की तरह। उनको म्यूटेट करने की बजाए, आ
`चैयाह` => `चाहिए`

2022-09-15 10:36 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +## स्टेट का रीड-ओनली व्यवहार करना  {/*treat-state-as-read-only*/}
`स्टेट का रीड-ओनली व्यवहार करना` => `स्टेट का रीड-ओनली मानें`

2022-09-15 10:36 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +दुसरे शब्दों में, आपको **स्टेट में मौजूद जावास्क्रिप्ट ऑब्जेक्ट के साथ हमेशा रीड-ओनली व्यवहार करना चैयाह**
`के साथ हमेशा रीड-ओनली व्यवहार करना चैयाह` => `को हमेशा रीड-ओनली मानना चाहिए`

2022-09-15 10:36 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +दिए गए  उदाहरण में, स्टेट में मोजूद ऑब्जेक्ट वर्तमान में  पॉइंटर का स्थान बता रहा है। मौजूद लाल बिंदु पर कर्सर टच या प्रीव्यू करने पे अपना स्थान बदलना छियाह। परन्तु बिंदु अपने स्थान पे ही रहती है:
`वर्तमान में पॉइंटर` => `करंट पॉइंटर`

2022-09-15 10:36 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +दिए गए  उदाहरण में, स्टेट में मोजूद ऑब्जेक्ट वर्तमान में  पॉइंटर का स्थान बता रहा है। मौजूद लाल बिंदु पर कर्सर टच या प्रीव्यू करने पे अपना स्थान बदलना छियाह। परन्तु बिंदु अपने स्थान पे ही रहती है:
`का स्थान` => `की पोजीशन`

2022-09-15 10:36 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +दिए गए  उदाहरण में, स्टेट में मोजूद ऑब्जेक्ट वर्तमान में  पॉइंटर का स्थान बता रहा है। मौजूद लाल बिंदु पर कर्सर टच या प्रीव्यू करने पे अपना स्थान बदलना छियाह। परन्तु बिंदु अपने स्थान पे ही रहती है:
`छियाह` => `चाहिए`

2022-09-15 10:36 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +दिए गए  उदाहरण में, स्टेट में मोजूद ऑब्जेक्ट वर्तमान में  पॉइंटर का स्थान बता रहा है। मौजूद लाल बिंदु पर कर्सर टच या प्रीव्यू करने पे अपना स्थान बदलना छियाह। परन्तु बिंदु अपने स्थान पे ही रहती है:
`रहती` => `रहता`

2022-09-15 10:36 UTC, arshadkazmi42 requested changes
Thank you for working on this fixes. 

I have added few more comments till line 104.

Let's get these fixed, then we can continue further with the review.

2022-09-15 10:36 UTC, arshadkazmi42 requested changes
Thank you for working on this fixes. 

I have added few more comments till line 104.

Let's get these fixed, then we can continue further with the review.

2022-09-16 17:54 UTC, Akshat2Jain commented
Hey @arshadkazmi42 sir, I have made changes. Plz review them so we can move forward.

2022-09-22 10:41 UTC, Akshat2Jain commented
Hey @arshadkazmi42 sir, Plz review the changes so that we can move forward with the process

2022-09-22 13:36 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +## म्युटेशन क्या होती है ?  {/*whats-a-mutation*/}
@Akshat2Jain There is a typo in this `होता है? ?` you have added two question marks

2022-09-22 13:37 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +तकनीकी ओर से यह मुमकिन है की _खुदी ऑब्जेक्ट_ के कंटेंट को चेंज करसके।  **यही म्युटेशन कहलाता है:**
@Akshat2Jain one typo here `चेंज कर सकते हैं।।` you have added two `।।` at the end

2022-09-22 13:39 UTC, arshadkazmi42 commented
@Akshat2Jain There is few minor typos in two of the fixes. Can you get those updated. Post that we will continue further

2022-09-22 14:07 UTC, arshadkazmi42 requested changes
Thank you for working on the fixes.

I have added more comments till ine 198.

Let's get these fixed and post that we will continue further

2022-09-22 14:07 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +दिया गया कोड शंशोदित करता है सोपे गए उस `स्थान` पे ऑब्जेक्ट को [पिछली रेंडर](/learn/state-as-a-snapshot#rendering-takes-a-snapshot-in-time) से। परन्तु बिना स्टेट सेटिंग फंक्शन का उपयोग करे, React को
`गढ़` => `आर्डर`

2022-09-22 14:07 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +दिया गया कोड शंशोदित करता है सोपे गए उस `स्थान` पे ऑब्जेक्ट को [पिछली रेंडर](/learn/state-as-a-snapshot#rendering-takes-a-snapshot-in-time) से। परन्तु बिना स्टेट सेटिंग फंक्शन का उपयोग करे, React को
`करता है। परन्तु असा करना हम` => `करता, परन्तु हम ऐसा करने का`

2022-09-22 14:07 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +वास्तव में [रे-रेंडर ट्रिगर](/learn/state-as-a-snapshot#setting-state-triggers-renders) करने के लिया , **एक *नया* ऑब्जेक्ट सर्जन करे और स्टेट सेटिंग फंक्शन में पास करदे:**
`सर्जन` => `बनाये`

2022-09-23 10:10 UTC, Akshat2Jain commented
Hey @arshadkazmi42 sir, I have made the changes. Plz review them so that we can move forward

2022-09-27 14:05 UTC, Akshat2Jain commented
Hey @arshadkazmi42 , Plz review the changes

2022-10-01 05:50 UTC, Akshat2Jain commented
Hello @arshadkazmi42 Sir, Plz review the changes

2022-10-01 07:51 UTC, arshadkazmi42 commented
> Hello @arshadkazmi42 Sir, Plz review the changes

Hi, I will review the changes ASAP. Have been a bit busy. 
Thank you for your patience.

2022-10-01 08:33 UTC, arshadkazmi42 requested changes
Thank you for working on the fixes.

I have added review till line 294

2022-10-01 08:33 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +## स्प्रेड सिंटैक्स के साथ ऑब्जेक्ट्स  की प्रतिलिपि बनाना {/*copying-objects-with-the-spread-syntax*/}
`की प्रतिलिपि बनाना` => `की ओपी बनाना`

2022-10-01 08:33 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +पिछले उदाहरण में, `स्थिति` ऑब्जेक्ट  हमेशा वर्तमान कर्सर स्थिति से ताजा बनाई जाती है। लेकिन अक्सर, आप अपने द्वारा बनाई जा रही नई ऑब्जेक्ट  के हिस्से के रूप में *मौजूदा* डेटा शामिल करना चाहेंगे। उदाहर
```
`स्थिति`
``` 
=> 
```
`position`
```

2022-10-01 08:33 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +पिछले उदाहरण में, `स्थिति` ऑब्जेक्ट  हमेशा वर्तमान कर्सर स्थिति से ताजा बनाई जाती है। लेकिन अक्सर, आप अपने द्वारा बनाई जा रही नई ऑब्जेक्ट  के हिस्से के रूप में *मौजूदा* डेटा शामिल करना चाहेंगे। उदाहर
`स्थिति` => `के स्थान`

2022-10-01 08:33 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +पिछले उदाहरण में, `स्थिति` ऑब्जेक्ट  हमेशा वर्तमान कर्सर स्थिति से ताजा बनाई जाती है। लेकिन अक्सर, आप अपने द्वारा बनाई जा रही नई ऑब्जेक्ट  के हिस्से के रूप में *मौजूदा* डेटा शामिल करना चाहेंगे। उदाहर
`बनाई जाती` => `बनाया जाता`

2022-10-01 08:33 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +पिछले उदाहरण में, `स्थिति` ऑब्जेक्ट  हमेशा वर्तमान कर्सर स्थिति से ताजा बनाई जाती है। लेकिन अक्सर, आप अपने द्वारा बनाई जा रही नई ऑब्जेक्ट  के हिस्से के रूप में *मौजूदा* डेटा शामिल करना चाहेंगे। उदाहर
`बनाई जा रही नई` => `बनाये जा रहे नए`

2022-10-01 08:33 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +पिछले उदाहरण में, `स्थिति` ऑब्जेक्ट  हमेशा वर्तमान कर्सर स्थिति से ताजा बनाई जाती है। लेकिन अक्सर, आप अपने द्वारा बनाई जा रही नई ऑब्जेक्ट  के हिस्से के रूप में *मौजूदा* डेटा शामिल करना चाहेंगे। उदाहर
`प्रपत्र` => `फॉर्म`

2022-10-01 08:33 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +पिछले उदाहरण में, `स्थिति` ऑब्जेक्ट  हमेशा वर्तमान कर्सर स्थिति से ताजा बनाई जाती है। लेकिन अक्सर, आप अपने द्वारा बनाई जा रही नई ऑब्जेक्ट  के हिस्से के रूप में *मौजूदा* डेटा शामिल करना चाहेंगे। उदाहर
`पिछले मान` => `पिछली वैल्यूज`

2022-10-01 08:33 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +ये इनपुट फ़ील्ड काम नहीं करते क्योंकि `ऑन चेंज` हैंडलर स्टेट  को बदलते हैं:
```
`ऑन चेंज`
```
=>
```
`onChange`
```

2022-10-01 08:33 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +आप जिस व्यवहार की तलाश कर रहे हैं उसे प्राप्त करने का विश्वसनीय तरीका एक नई ऑब्जेक्ट  बनाना और उसे 'सेटपर्सन' को पास करना है। लेकिन यहां, आप **मौजूदा डेटा को इसमें कॉपी करना चाहते हैं** क्योंकि केवल
`नई` => `नया`

2022-10-01 08:33 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +आप जिस व्यवहार की तलाश कर रहे हैं उसे प्राप्त करने का विश्वसनीय तरीका एक नई ऑब्जेक्ट  बनाना और उसे 'सेटपर्सन' को पास करना है। लेकिन यहां, आप **मौजूदा डेटा को इसमें कॉपी करना चाहते हैं** क्योंकि केवल
```
'सेटपर्सन'
```
=>
```
`setPerson`
```

2022-10-01 08:33 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +आप जिस व्यवहार की तलाश कर रहे हैं उसे प्राप्त करने का विश्वसनीय तरीका एक नई ऑब्जेक्ट  बनाना और उसे 'सेटपर्सन' को पास करना है। लेकिन यहां, आप **मौजूदा डेटा को इसमें कॉपी करना चाहते हैं** क्योंकि केवल
`बदल गई` => `बदला`

2022-10-01 08:33 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +अब फॉर्म काम करता है!
`करता` => `कर रहा`

2022-10-05 10:37 UTC, Akshat2Jain commented
Hey @arshadkazmi42 sir, I have made the changes. Plz review them

2022-10-09 10:18 UTC, Akshat2Jain commented
Hello @arshadkazmi42 sir, Plz review the changes

2022-10-09 11:20 UTC, arshadkazmi42 requested changes
Thank you for working on the fixes.

I have added more reviews till line 470.

Lets get these fixed and then we can continue further with the review.

2022-10-09 11:20 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +ध्यान दें कि आपने प्रत्येक इनपुट फ़ील्ड के लिए एक अलग स्टेट वैल्यू  घोषित नहीं किया। बड़े रूपों के लिए, सभी डेटा को किसी ऑब्जेक्ट में समूहीकृत रखना बहुत सुविधाजनक है--जब तक आप इसे सही तरीके से अपडेट
`घोषित` => `डिक्लेअर`

2022-10-09 11:20 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +ध्यान दें कि आपने प्रत्येक इनपुट फ़ील्ड के लिए एक अलग स्टेट वैल्यू  घोषित नहीं किया। बड़े रूपों के लिए, सभी डेटा को किसी ऑब्जेक्ट में समूहीकृत रखना बहुत सुविधाजनक है--जब तक आप इसे सही तरीके से अपडेट
`रूपों` => `फॉर्म्स`

2022-10-09 11:20 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +ध्यान दें कि आपने प्रत्येक इनपुट फ़ील्ड के लिए एक अलग स्टेट वैल्यू  घोषित नहीं किया। बड़े रूपों के लिए, सभी डेटा को किसी ऑब्जेक्ट में समूहीकृत रखना बहुत सुविधाजनक है--जब तक आप इसे सही तरीके से अपडेट
`समूहीकृत` => `एक साथ ग्रुप में`

2022-10-09 11:20 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +ध्यान दें कि `...` स्प्रेड सिंटैक्स "उथला" है - यह केवल चीजों को एक स्तर की गहराई तक कॉपी करता है। यह इसे तेज़ बनाता है, लेकिन इसका मतलब यह भी है कि यदि आप किसी नेस्टेड प्रॉपर्टी को अपडेट करना चाहते
`उथला` => `shallow`

2022-10-09 11:20 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +ध्यान दें कि `...` स्प्रेड सिंटैक्स "उथला" है - यह केवल चीजों को एक स्तर की गहराई तक कॉपी करता है। यह इसे तेज़ बनाता है, लेकिन इसका मतलब यह भी है कि यदि आप किसी नेस्टेड प्रॉपर्टी को अपडेट करना चाहते
`स्तर` => `लेवल`

2022-10-09 11:20 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +आप डायनामिक नाम वाली किसी प्रॉपर्टी को निर्दिष्ट करने के लिए अपनी ऑब्जेक्ट परिभाषा के अंदर `[` और `]` ब्रेसिज़ का भी उपयोग कर सकते हैं। यहां एक ही उदाहरण है, लेकिन तीन अलग-अलग लोगों के बजाय एक ही ईवे
`अपनी ऑब्जेक्ट परिभाषा` => `अपने ऑब्जेक्ट डेफिनिशन`

2022-10-09 11:20 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +यहां, `e.target.name` का मतलब `नाम` प्रॉपर्टी  है जो `<input>` DOM तत्व को दी गई है।
`नाम` => `name`

2022-10-09 11:20 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +यहां, `e.target.name` का मतलब `नाम` प्रॉपर्टी  है जो `<input>` DOM तत्व को दी गई है।
`तत्व` => `एलिमेंट`

2022-10-09 11:20 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +इस तरह एक नेस्टेड ऑब्जेक्ट  संरचना पर विचार करें:
`संरचना` => `स्ट्रक्चर`

2022-10-09 11:20 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +यदि आप `person.artwork.city` को अपडेट करना चाहते हैं, तो यह स्पष्ट है कि इसे उत्परिवर्तन के साथ कैसे किया जाए:
`उत्परिवर्तन` => `म्युटेशन`

2022-10-09 11:20 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +लेकिन React  में, आप ऑब्जेक्ट  को अपरिवर्तनीय मानते हैं! `शहर` को बदलने के लिए, आपको पहले नई `कलाकृति` ऑब्जेक्ट  (पिछले एक से डेटा के साथ पूर्व-आबादी) का उत्पादन करना होगा, और फिर नई `व्यक्ति` ऑब्जेक
`शहर` => `city`

2022-10-09 11:20 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +लेकिन React  में, आप ऑब्जेक्ट  को अपरिवर्तनीय मानते हैं! `शहर` को बदलने के लिए, आपको पहले नई `कलाकृति` ऑब्जेक्ट  (पिछले एक से डेटा के साथ पूर्व-आबादी) का उत्पादन करना होगा, और फिर नई `व्यक्ति` ऑब्जेक
`कलाकृति` => `artwork`

2022-10-09 11:20 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +लेकिन React  में, आप ऑब्जेक्ट  को अपरिवर्तनीय मानते हैं! `शहर` को बदलने के लिए, आपको पहले नई `कलाकृति` ऑब्जेक्ट  (पिछले एक से डेटा के साथ पूर्व-आबादी) का उत्पादन करना होगा, और फिर नई `व्यक्ति` ऑब्जेक
`पिछले एक से डेटा के साथ पूर्व-आबादी` => `पिछले वाले से प्री-पॉपुलटेड डेटा के साथ`

2022-10-09 11:20 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +लेकिन React  में, आप ऑब्जेक्ट  को अपरिवर्तनीय मानते हैं! `शहर` को बदलने के लिए, आपको पहले नई `कलाकृति` ऑब्जेक्ट  (पिछले एक से डेटा के साथ पूर्व-आबादी) का उत्पादन करना होगा, और फिर नई `व्यक्ति` ऑब्जेक
`व्यक्ति` => `person`

2022-10-09 11:20 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +लेकिन React  में, आप ऑब्जेक्ट  को अपरिवर्तनीय मानते हैं! `शहर` को बदलने के लिए, आपको पहले नई `कलाकृति` ऑब्जेक्ट  (पिछले एक से डेटा के साथ पूर्व-आबादी) का उत्पादन करना होगा, और फिर नई `व्यक्ति` ऑब्जेक
`कलाकृति` => `artwork`

2022-10-09 11:20 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +लेकिन React  में, आप ऑब्जेक्ट  को अपरिवर्तनीय मानते हैं! `शहर` को बदलने के लिए, आपको पहले नई `कलाकृति` ऑब्जेक्ट  (पिछले एक से डेटा के साथ पूर्व-आबादी) का उत्पादन करना होगा, और फिर नई `व्यक्ति` ऑब्जेक
`इंगित` => `पॉइंट`

2022-10-11 17:55 UTC, Akshat2Jain commented
Hey @arshadkazmi42 sir, I have done the changes. Plz review them so that we can move forward

2022-10-15 16:48 UTC, Akshat2Jain commented
Hello @arshadkazmi42 sir, Plz review the changes so that we can move forward

2022-10-15 20:14 UTC, arshadkazmi42 requested changes
Sorry for the late review and thank you for working on the fixes.

I have added more reviews till line 674.

Lets get these fixed and then we can proceed further.

2022-10-15 20:14 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +### Immer के साथ संक्षिप्त अद्यतन तर्क लिखें {/*write-concise-update-logic-with-immer*/}
`अद्यतन तर्क` => `अपडेट लॉजिक`

2022-10-15 20:14 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +यदि आपका स्टेट  गहरा नेस्टेड  है, तो आप [इसे समतल करना](/learn/choosing-the-state-structure#avoid-deeply-nested-state) पर विचार करना चाहेंगे। लेकिन, यदि आप अपनी स्टेट  संरचना को बदलना नहीं चाहते हैं,
`गहरा` => `ज़्यादा`

2022-10-15 20:14 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +यदि आपका स्टेट  गहरा नेस्टेड  है, तो आप [इसे समतल करना](/learn/choosing-the-state-structure#avoid-deeply-nested-state) पर विचार करना चाहेंगे। लेकिन, यदि आप अपनी स्टेट  संरचना को बदलना नहीं चाहते हैं,
`समतल करना` => `फ्लाय्टन करने`

2022-10-15 20:14 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +यदि आपका स्टेट  गहरा नेस्टेड  है, तो आप [इसे समतल करना](/learn/choosing-the-state-structure#avoid-deeply-nested-state) पर विचार करना चाहेंगे। लेकिन, यदि आप अपनी स्टेट  संरचना को बदलना नहीं चाहते हैं,
`संरचना`  => `स्ट्रक्चर`

2022-10-15 20:14 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +यदि आपका स्टेट  गहरा नेस्टेड  है, तो आप [इसे समतल करना](/learn/choosing-the-state-structure#avoid-deeply-nested-state) पर विचार करना चाहेंगे। लेकिन, यदि आप अपनी स्टेट  संरचना को बदलना नहीं चाहते हैं,
`इमर` => `Immer`

2022-10-15 20:14 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +यदि आपका स्टेट  गहरा नेस्टेड  है, तो आप [इसे समतल करना](/learn/choosing-the-state-structure#avoid-deeply-nested-state) पर विचार करना चाहेंगे। लेकिन, यदि आप अपनी स्टेट  संरचना को बदलना नहीं चाहते हैं,
`परिवर्तनशील` => `मुटेटिंग`

2022-10-15 20:14 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +यदि आपका स्टेट  गहरा नेस्टेड  है, तो आप [इसे समतल करना](/learn/choosing-the-state-structure#avoid-deeply-nested-state) पर विचार करना चाहेंगे। लेकिन, यदि आप अपनी स्टेट  संरचना को बदलना नहीं चाहते हैं,
`प्रतियां तैयार करने` => `कॉपीस बनाने`

2022-10-15 20:14 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +यदि आपका स्टेट  गहरा नेस्टेड  है, तो आप [इसे समतल करना](/learn/choosing-the-state-structure#avoid-deeply-nested-state) पर विचार करना चाहेंगे। लेकिन, यदि आप अपनी स्टेट  संरचना को बदलना नहीं चाहते हैं,
`वस्तु को बदल` => `ऑब्जेक्ट को मुटेट`

2022-10-15 20:14 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +लेकिन एक नियमित उत्परिवर्तन के विपरीत, यह पिछली स्थिति को अधिलेखित नहीं करता है!
`नियमित उत्परिवर्तन` => `रेगुलर म्युटेशन`

2022-10-15 20:14 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +लेकिन एक नियमित उत्परिवर्तन के विपरीत, यह पिछली स्थिति को अधिलेखित नहीं करता है!
`पिछली स्थिति` => `पिछले स्टेट`

2022-10-15 20:14 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +लेकिन एक नियमित उत्परिवर्तन के विपरीत, यह पिछली स्थिति को अधिलेखित नहीं करता है!
`अधिलेखित` => `ओवरराईट`

2022-10-15 20:14 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +Immer द्वारा प्रदान किया गया `ड्राफ़्ट` एक विशेष प्रकार की ऑब्जेक्ट  है, जिसे [प्रॉक्सी](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) कहा जाता है, जो "रिकॉर
`की` => `का`

2022-10-15 20:14 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +Immer द्वारा प्रदान किया गया `ड्राफ़्ट` एक विशेष प्रकार की ऑब्जेक्ट  है, जिसे [प्रॉक्सी](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) कहा जाता है, जो "रिकॉर
`प्रॉक्सी` => `Proxy`

2022-10-15 20:14 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +Immer द्वारा प्रदान किया गया `ड्राफ़्ट` एक विशेष प्रकार की ऑब्जेक्ट  है, जिसे [प्रॉक्सी](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) कहा जाता है, जो "रिकॉर
`जो "रिकॉर्ड करता है" "आप इसके साथ क्या करते हैं।` => `जो आप इसके साथ क्या करते हैं उसे "रिकॉर्ड करता है"`

2022-10-15 20:14 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +Immer द्वारा प्रदान किया गया `ड्राफ़्ट` एक विशेष प्रकार की ऑब्जेक्ट  है, जिसे [प्रॉक्सी](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) कहा जाता है, जो "रिकॉर
`संपादन` => `बदलाव`

2022-10-15 20:14 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +1. डिपेंडेंसी  के रूप में अपने `package.json` में `use-immer` जोड़ें
`जोड़ें` => `ऐड करें`

2022-10-15 20:14 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +2. रन `एनपीएम इंस्टॉल
```
रन `एनपीएम इंस्टॉल
```
=>
```
`npm install` रन करें
```

2022-10-15 20:14 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +3. फिर `import {useState} को 'react' से बदलकर `import {useImmer} से 'use-immer'` से बदलें
```
फिर `import {useState} को 'react' से बदलकर `import {useImmer} से 'use-immer'` से बदलें
```
=>
```
फिर `import {useState} from 'react'` से बदलकर `import {useImmer} from 'use-immer'` से बदलें
```

2022-10-15 20:14 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +यहाँ उदाहरण Immer में परिवर्तित किया गया है:
`यहाँ उदाहरण` => `यहाँ ऊपर दिया गया उदाहरण`

2022-10-20 04:10 UTC, Akshat2Jain commented
Hey @arshadkazmi42 sir, I have made the changes plz review them so that we can move forward

2022-10-20 11:35 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +
@Akshat2Jain You have missed this

2022-10-20 11:37 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +
Actually you haven't missed this, the lines have changed due to previous fixes.

To exactly update this,

- Move this line `### Immer के साथ संक्षिप्त अपडेट लॉजिक लिखें {/*write-concise-update-logic-with-immer*/}` to line 647

2022-10-20 12:32 UTC, Akshat2Jain commented
I have fixed the changes. Plz review them

2022-10-20 12:35 UTC, arshadkazmi42 requested changes
Great work with the fixes.

Add the review to the test of the file.

Once these are fixed, we can get this merged.

2022-10-20 12:35 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +* **आवश्यकता परिवर्तन:** कुछ एप्लिकेशन सुविधाएं, जैसे पूर्ववत करें/फिर से करें को लागू करना, परिवर्तनों का इतिहास दिखाना, या उपयोगकर्ता को किसी फ़ॉर्म को पहले के मानों पर रीसेट करने देना, तब करना आसा
```suggestion
* **आवश्यकता परिवर्तन:** कुछ एप्लिकेशन फीचर्स, जैसे Undo/Redo, परिवर्तनों की हिस्ट्री दिखाना, या यूज़र्स को किसी फ़ॉर्म को के पहले की वैल्यूज पर रीसेट करने देना, तब करना आसान होता है जब कुछ भी म्यूटेट नहीं होता है। ऐसा इसलिए है क्योंकि आप स्टेट  की पिछली कॉपीस को मेमोरी में रख सकते हैं, और उपयुक्त होने पर उनका पुन: उपयोग कर सकते हैं। यदि आप एक म्यूटेटिव अप्रोच से शुरू करते हैं, तो इस तरह के फीचर्स को बाद में ऐड करना मुश्किल हो सकता है।
```

2022-10-20 12:35 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +* **सरल कार्यान्वयन:** क्योंकि React  म्यूटेशन पर निर्भर नहीं है, इसलिए इसे आपकी वस्तुओं के साथ कुछ खास करने की आवश्यकता नहीं है। इसे अपनी संपत्तियों को हाईजैक करने की आवश्यकता नहीं है, हमेशा उन्हें
```suggestion
* **सरल इम्प्लीमेंटेशन:** क्योंकि React म्यूटेशन पर निर्भर नहीं है, इसलिए इसे आपकी ऑब्जेक्ट्स के साथ कुछ खास करने की आवश्यकता नहीं है। इसे अपनी प्रॉपर्टीज को हाईजैक करने की आवश्यकता नहीं है, हमेशा उन्हें Proxies में लपेटें, या प्रारंभ में अन्य कार्य करें जैसा कि कई "रिएक्टिव" समाधान करते हैं। यही कारण है कि React आपको किसी भी ऑब्जेक्ट को स्टेट में रखने देता है - चाहे वह कितना भी बड़ा हो - बिना अतिरिक्त परफॉरमेंस या करेक्टनेस के नुकसान के।
```

2022-10-20 12:35 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +व्यवहार में, आप अक्सर React  में उत्परिवर्तित अवस्था के साथ "दूर हो सकते हैं", लेकिन हम आपको दृढ़ता से सलाह देते हैं कि आप ऐसा न करें ताकि आप इस दृष्टिकोण को ध्यान में रखते हुए विकसित नई React  सुविध
```suggestion
व्यवहार में, आप अक्सर React  में म्यूटेटिंग स्टेट के साथ "काम चला सकते हैं", लेकिन हम आपको दृढ़ता से सलाह देते हैं कि आप ऐसा न करें ताकि आप इस अप्रोच को ध्यान में रखते हुए बनाये गए नए React फीचर्स का उपयोग कर सकें। भविष्य के कॉंट्रिब्युटर्स और शायद आप खुद भी भविष्य अपने आपको धन्यवाद देंगे!
```

2022-10-20 12:35 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +* Recat में सभी स्टेट  को अपरिवर्तनीय मानें।
```suggestion
* React में सभी स्टेट को अपरिवर्तनीय मानें।
```

2022-10-20 12:35 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +* जब आप ऑब्जेक्ट  को स्टेट  में संग्रहीत करते हैं, तो उन्हें उत्परिवर्तित करने से रेंडर ट्रिगर नहीं होंगे और पिछले रेंडर "स्नैपशॉट्स" में स्थिति बदल जाएगी।
```suggestion
* जब आप ऑब्जेक्ट को स्टेट में स्टोर करते हैं, तो उन्हें म्यूटेट करने से रेंडर ट्रिगर नहीं होंगे और पिछले रेंडर "स्नैपशॉट्स" में स्थिति बदल जाएगी।
```

2022-10-20 12:35 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +* किसी ऑब्जेक्ट को बदलने के बजाय, उसका एक *नया* संस्करण बनाएं, और उस पर स्थिति सेट करके एक री-रेंडर को ट्रिगर करें।
```suggestion
* किसी ऑब्जेक्ट को बदलने के बजाय, उसका एक *नया* वर्शन बनाएं, और उस पर स्टेट को सेट करके एक री-रेंडर को ट्रिगर करें।
```

2022-10-20 12:35 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +* आप ऑब्जेक्ट  की प्रतियां बनाने के लिए `{...obj, कुछ: 'newValue'}` ऑब्जेक्ट स्प्रेड सिंटैक्स का उपयोग कर सकते हैं।
```suggestion
* आप ऑब्जेक्ट की कॉपीस बनाने के लिए ऑब्जेक्ट स्प्रेड सिंटैक्स `{...obj, something: 'newValue'}` का उपयोग कर सकते हैं।
```

2022-10-20 12:35 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +* स्प्रेड सिंटैक्स उथला है: यह केवल एक स्तर को गहराई से कॉपी करता है।
```suggestion
* स्प्रेड सिंटैक्स शैलो है: यह केवल एक लेवल तक की गहराई से कॉपी करता है।
```

2022-10-20 12:35 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +* दोहराए जाने वाले प्रतिलिपि कोड को कम करने के लिए, Immer का उपयोग करें।
```suggestion
* रिपीट होने वाले कोड को कम करने के लिए, Immer का उपयोग करें।
```

2022-10-20 12:35 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +### गलत स्थिति अपडेट को ठीक करें {/*fix-incorrect-state-updates*/}
```suggestion
### गलत स्टेट अपडेट को ठीक करना {/*fix-incorrect-state-updates*/}
```

2022-10-20 12:35 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +इस फॉर्म में कुछ बग हैं। उस बटन पर क्लिक करें जो स्कोर को कुछ गुना बढ़ा देता है। ध्यान दें कि यह नहीं बढ़ता है। फिर पहले नाम को संपादित करें, और ध्यान दें कि आपके परिवर्तनों के साथ स्कोर अचानक "पकड़
```suggestion
इस फॉर्म में कुछ बग हैं। उस बटन पर क्लिक करें जो स्कोर को कुछ गुना बढ़ा देता है। ध्यान दें कि यह नहीं बढ़ता है। फिर पहले नाम को एडिट करें, और ध्यान दें कि आपके परिवर्तनों के साथ स्कोर अचानक "आपके बदलाव के अनुसार सही हो गया" है। अंत में, अंतिम नाम एडिट करें, और ध्यान दें कि स्कोर पूरी तरह से गायब हो गया है।
```

2022-10-20 12:35 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +आपका काम इन सभी बगों को ठीक करना है। जैसे ही आप उन्हें ठीक करते हैं, समझाएं कि उनमें से प्रत्येक क्यों होता है।
```suggestion
आपका काम इन सभी बगों को ठीक करना है। जैसे-जैसे  आप उन्हें ठीक करते हैं, यह समझाएं कि उनमें से प्रत्येक क्यों होते हैं।
```

2022-10-20 12:35 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +यहाँ एक संस्करण है जिसमें दोनों बग फिक्स हैं:
```suggestion
यहाँ एक वर्शन है जिसमें दोनों बग फिक्स हैं:
```

2022-10-20 12:35 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +`हैंडलप्लसक्लिक` के साथ समस्या यह थी कि इसने `प्लेयर` ऑब्जेक्ट को बदल दिया। नतीजतन, रिएक्ट को यह नहीं पता था कि फिर से रेरेन्दर  करने का एक कारण है, और स्क्रीन पर स्कोर को अपडेट नहीं किया। यही कारण ह
```suggestion
`handlePlusClick` के साथ समस्या यह थी कि इसने `player` ऑब्जेक्ट को बदल दिया। जिसकी वजह से, React को यह नहीं पता था कि फिर से री-रेंडर करने का एक कारण है, और स्क्रीन पर स्कोर को अपडेट नहीं किया। यही कारण है कि, जब आपने पहले नाम को एडिट किया, तो स्टेट अपडेट हो गया, एक री-रेंडर को _भी_ ट्रिगर किया जिसने स्क्रीन पर स्कोर को अपडेट किया।
```

2022-10-20 12:35 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +`हैंडललास्टनाम चेंज` के साथ समस्या यह थी कि इसने मौजूदा `...प्लेयर` फ़ील्ड को नए ऑब्जेक्ट में कॉपी नहीं किया। यही कारण है कि आपके द्वारा अंतिम नाम संपादित करने के बाद स्कोर खो गया है।
```suggestion
`handleLastNameChange` के साथ समस्या यह थी कि इसने मौजूदा `...player` फ़ील्ड को नए ऑब्जेक्ट में कॉपी नहीं किया। यही कारण है कि आपके द्वारा अंतिम नाम एडिट करने के बाद स्कोर गायब हो गया।
```

2022-10-20 12:35 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +### उत्परिवर्तन खोजें और ठीक करें {/*find-and-fix-the-mutation*/}
```suggestion
### म्यूटेशन ढूंढे और ठीक करें {/*find-and-fix-the-mutation*/}
```

2022-10-20 12:35 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +लेकिन एक बग है। यदि आप पहले बॉक्स को घुमाते हैं, और फिर उसका रंग बदलते हैं, तो बैकग्राउंड (जिसे हिलना नहीं चाहिए!) बॉक्स की स्थिति में "कूद" जाएगा। लेकिन ऐसा नहीं होना चाहिए: 'बैकग्राउंड' का 'पोजिशन'
```suggestion
लेकिन एक बग है। यदि आप पहले बॉक्स को घुमाते हैं, और फिर उसका रंग बदलते हैं, तो बैकग्राउंड (जिसे हिलना नहीं चाहिए!) बॉक्स की जगह पर "कूद" जाएगा। लेकिन ऐसा नहीं होना चाहिए: 'Background' का 'position' prop 'initialPosition' पर सेट है, जो कि '{ x: 0, y: 0 }' है। रंग बदलने के बाद बैकग्राउंड क्यों हिल रहा है?
```

2022-10-20 12:35 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +यदि कुछ अनपेक्षित परिवर्तन होता है, तो एक म्युटेशन  होता है। `App.js` में उत्परिवर्तन खोजें और इसे ठीक करें।
```suggestion
यदि कुछ अनएक्सपेक्टेड बदलता होता है, तो एक म्युटेशन होता है।`App.js` में म्यूटेशन ढूंढे और उसे ठीक करें।
```

2022-10-20 12:35 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +समस्या `हैंडलमोव` के अंदर उत्परिवर्तन में थी। इसने `shape.position` को बदल दिया, लेकिन यह वही ऑब्जेक्ट  है जिस पर `initialPosition` इंगित करता है। यही कारण है कि आकार और बैकग्राउंड  दोनों चलते हैं। (
```suggestion
समस्या `handleMove` के अंदर म्यूटेशन में थी। इसने `shape.position` को बदल दिया, लेकिन यह वही ऑब्जेक्ट  है जिस पर `initialPosition` पॉइंट करता है। यही कारण है कि शेप और बैकग्राउंड दोनों मूव होते हैं। (यह एक म्यूटेशन है, इसलिए परिवर्तन एक अनरिलेटेड अपडेट तक स्क्रीन पर रिफ्लेक्ट नहीं होता है--रंग परिवर्तन--एक री-रेंडर ट्रिगर करता है।)
```

2022-10-20 12:35 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +फिक्स म्यूटेशन को `हैंडलमोव` से हटाना है, और आकृति को कॉपी करने के लिए स्प्रेड सिंटैक्स का उपयोग करना है। ध्यान दें कि `+=` एक उत्परिवर्तन है, इसलिए आपको नियमित `+` ऑपरेशन का उपयोग करने के लिए इसे फि
```suggestion
इसका फिक्स म्यूटेशन को `handleMove` से हटाना है, और shape को कॉपी करने के लिए स्प्रेड सिंटैक्स का उपयोग करना है। ध्यान दें कि `+=` एक म्यूटेशन है, इसलिए आपको नियमित `+` ऑपरेशन का उपयोग करने के लिए इसे फिर से लिखना होगा।
```

2022-10-20 12:35 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +पिछली चुनौती की तरह यह वही buggy  उदाहरण है। इस बार, इमर का उपयोग करके उत्परिवर्तन को ठीक करें। आपकी सुविधा के लिए, `useImmer` पहले से ही आयात किया जा चुका है, इसलिए इसका उपयोग करने के लिए आपको `आकार
```suggestion
पिछले चैलेंज की तरह यह वही buggy उदाहरण है। इस बार, Immer का उपयोग करके म्यूटेशन को ठीक करें। आपकी सुविधा के लिए, `useImmer` पहले से ही इम्पोर्ट किया जा चुका है, इसलिए इसका उपयोग करने के लिए आपको `shape` स्टेट वेरिएबल को बदलना होगा।
```

2022-10-20 12:35 UTC, arshadkazmi42 commented on beta/src/pages/learn/updating-objects-in-state.md
> +यह इमर के साथ फिर से लिखा गया समाधान है। ध्यान दें कि कैसे ईवेंट हैंडलर एक परिवर्तनशील तरीके से लिखे जाते हैं, लेकिन बग नहीं होता है। ऐसा इसलिए है क्योंकि हुड के निचे , इमर मौजूदा ऑब्जेक्ट्स  को कभी
```suggestion
यह Immer के साथ फिर से लिखा गया समाधान है। ध्यान दें कि कैसे ईवेंट हैंडलर एक म्यूटेटिंग तरीके से लिखे जाते हैं, लेकिन बग नहीं आता है। ऐसा इसलिए है क्योंकि हुड के निचे , Immer मौजूदा ऑब्जेक्ट्स को कभी भी म्यूटेट नहीं करता है।
```

2022-11-01 16:33 UTC, Akshat2Jain commented
Hey @arshadkazmi42 sir, I have fixed the changes. Please, review them so that we can merge this.

2022-11-01 18:19 UTC, arshadkazmi42 approved these changes
Great work. :rocket: 

Thank you for working on all the fixes.

Lets get this merged :tada:

2022-11-01 18:34 UTC, merged

2022-11-01 18:44 UTC, Akshat2Jain commented
Thanks For merging the Pr. 
Thank You @arshadkazmi42  Sir for guiding me. It's an achievement for me to contribute to the community.